name: CI Voll Med

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configura JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configura Docker Compose
        run: |
          if [ -f /usr/local/bin/docker-compose ]; then
              sudo rm /usr/local/bin/docker-compose
            else
              echo "Docker Compose não encontrado, prosseguindo..."
            fi
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Roda Docker Compose
        run: docker-compose up -d

      - name: Executa testes unitários
        run: mvn -B verify
    
      - name: Analize Estatica
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tmartins1_vollmed-api
